### ISSUE TITLE
pydantic.env_settings.SettingsError: error parsing JSON for "nickname"

### ISSUE THREAD

**Issue by danuonuo** [he0119/CoolQBot#74]
我已经在配置文件设置了nickname，安装了依赖，但启动报错：
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/config.py", line 70, in _build_environ
    env_val = self.__config__.json_loads(env_val)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/__init__.py", line 46, in run
    run_bot(file, app)
  File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers.py", line 44, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./bot.py", line 6, in <module>
    nonebot.init()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/__init__.py", line 177, in init
    config = Config(**kwargs,
  File "pydantic/env_settings.py", line 35, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 48, in pydantic.env_settings.BaseSettings._build_values
  File "/usr/local/lib/python3.8/dist-packages/nonebot/config.py", line 72, in _build_environ
    raise SettingsError(
**pydantic.env_settings.SettingsError: error parsing JSON for "nickname"**

**Comment by he0119** [comment]
诶，这个报错说你填写的不符合json格式。你配置文件怎么填的？

**Comment by danuonuo** [comment]
> 诶，这个报错说你填写的不符合json格式。你配置文件怎么填的？

_这个issue的问题已经解决，谢谢大佬_
另外，大佬，我有个小建议，可否将这个插件做成一个nb-cli插件的形式，同时提供两种方式使用（一种用nb-cli，另一种直接clone项目运行bot.py）这样会降低入门门槛的

**Comment by he0119** [comment]
不客气，那我关闭了。
插件的话，我这个仓库主要是放我自己群里的机器人方便管理和打包，独立成插件也麻烦就没弄了（如果你觉得什么功能有意思，可以直接参考）。
至于直接克隆后使用，我记得是可以的，README 里应该有提到。

**Comment by Flower-Brother** [comment]
我发现并解决了这个bug，是因为用了单引号（不知道是不是因为这个原因）
Javascript 在很多时候会把 JSON 对象里面没有双引号包围的值，当做数值处理。

下面是我的代码
# SUPERUSERS=['123456']  # 超级用户
NICKNAME=['小杏']  # 机器人昵称  # 这个地方报错了
NICKNAME=[" robot fafa "]  # 这样就没有报错了

第一次在GitHub发言，好紧张
